# Generated by Django 4.2.5 on 2023-09-28 09:42

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_project', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precast_number', models.CharField(max_length=100)),
                ('precast_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.get_file_path)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('Yet_to_start', models.BooleanField(default=False, help_text='0=default,1=show_status')),
                ('Design_done', models.BooleanField(default=False, help_text='0=default,1=show_status')),
                ('Precast_done', models.BooleanField(default=False, help_text='0=default,1=show_status')),
                ('Moving_to_site', models.BooleanField(default=False, help_text='0=default,1=show_status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
        ),
    ]
