# Generated by Django 4.2.5 on 2023-10-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_precast_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
